# GitHub Copilot Setup Steps for Pup Cid's Little TikTok Helper
# This file helps GitHub Copilot understand the repository structure and provide better assistance

name: Pup Cid's Little TikTok Helper Setup

description: |
  Professional TikTok LIVE streaming tool with overlays, alerts, TTS, automation and plugin system.
  Built with Node.js, Express, Socket.io, SQLite, and TikTok LIVE Connector.

# Project Overview
overview:
  stack:
    - Node.js (>=18.0.0 <24.0.0)
    - Express.js
    - Socket.io
    - SQLite (WAL mode)
    - TikTok LIVE Connector
    - Go (launcher only)
  
  main_technologies:
    - Backend: Express.js server with Socket.io for real-time communication
    - Database: SQLite with better-sqlite3
    - Frontend: Bootstrap 5, jQuery, Tailwind CSS
    - Automation: Flow engine for event-based automation
    - Plugins: Modular plugin system with lifecycle management
    - TTS: Text-to-Speech with multiple engines (TikTok TTS, Google Cloud TTS)
    - OBS: OBS WebSocket v5 integration
    - VR: VDO.Ninja and OSC bridge for VRChat integration

# Setup Steps
setup:
  # 1. Prerequisites
  prerequisites:
    - step: Install Node.js
      description: Node.js version 18.x, 20.x, or 22.x is required
      verification: node --version
      
    - step: Install npm dependencies
      description: All dependencies are installed automatically by the launcher
      command: npm install
      directory: app/
      
  # 2. Quick Start
  quick_start:
    windows:
      - Double-click start.exe OR run start.bat
      - The launcher automatically installs dependencies and starts the server
      
    linux:
      - Run ./start-linux OR ./start.sh
      - The launcher automatically installs dependencies and starts the server
      
    mac:
      - Run ./start-mac OR ./start.sh
      - The launcher automatically installs dependencies and starts the server
      
  # 3. Development Environment
  development:
    - step: Navigate to app directory
      command: cd app/
      
    - step: Install dependencies
      command: npm install
      
    - step: Copy environment template
      command: cp .env.example .env
      description: Configure TikTok session ID and other settings
      
    - step: Run in development mode
      command: npm run dev
      description: Starts server with nodemon for auto-reload
      
    - step: Build CSS (optional)
      command: npm run build:css
      description: Compile Tailwind CSS
      
    - step: Watch CSS (optional)
      command: npm run watch:css
      description: Auto-compile Tailwind CSS on changes

# Key Files and Directories
structure:
  root:
    - launcher.go: Go-based launcher that checks Node.js and manages dependencies
    - start.exe: Compiled launcher for Windows
    - start-linux: Compiled launcher for Linux
    - start-mac: Compiled launcher for macOS
    - start.bat: Fallback batch script for Windows
    - start.sh: Fallback shell script for Linux/Mac
    
  app:
    description: Main Node.js application
    key_files:
      - server.js: Main Express server entry point
      - launch.js: Application launcher script
      - package.json: Node.js dependencies and scripts
      - llm_start_here.md: Developer guide for AI assistants (READ THIS FIRST!)
      
    subdirectories:
      modules:
        description: Core application modules
        examples:
          - database.js: SQLite database management
          - tiktok.js: TikTok LIVE Connector integration
          - tts.js: Text-to-Speech engine
          - alerts.js: Alert manager
          - flows.js: Event-based automation engine
          - obs-websocket.js: OBS WebSocket integration
          - plugin-loader.js: Plugin system with lifecycle management
          - logger.js: Winston logger with daily rotation
          
      plugins:
        description: Modular plugin system
        structure: |
          plugins/<plugin-id>/
          ├── plugin.json       # Metadata (id, name, version, entry)
          ├── main.js           # Plugin class with init() and destroy()
          ├── ui.html           # Optional: Admin UI
          └── assets/           # Optional: CSS, JS, Images
        examples:
          - api-bridge: RESTful API for external integrations
          - clarityhud: VR-optimized overlays for VRChat
          - emoji-rain: Physics-based emoji rain effect
          - goals: Interactive goal tracking
          - hybridshock: OpenShock haptic feedback integration
          - multicam: Multi-camera switcher via gifts/commands
          - osc-bridge: Bidirectional OSC communication for VRChat
          - soundboard: Sound effect management
          - tts: TTS engine as plugin
          - weather-control: Professional weather effects system
          
      routes:
        description: Express route handlers
        examples:
          - plugin-routes.js: Plugin management API
          
      public:
        description: Frontend files
        key_files:
          - index.html: Main dashboard
          - overlay.html: OBS browser source overlay
          - css/: Stylesheets (Bootstrap, Tailwind)
          - js/: Client-side JavaScript
          
      data:
        description: Static data files
        
      docs:
        description: Documentation
        
      locales:
        description: Internationalization (i18n) files
        languages: [de, en]
        
      test:
        description: Test files
        
      scripts:
        description: Utility scripts
        
  github:
    description: GitHub workflows and configuration
    workflows:
      - soundboard-ci.yml: CI/CD for soundboard plugin

# Development Guidelines
guidelines:
  architecture:
    - Follow the plugin-based architecture
    - Each plugin should be self-contained with plugin.json and main.js
    - Use the PluginAPI for registering routes, sockets, and TikTok events
    
  code_style:
    - Use ES6+ JavaScript features
    - Follow existing code formatting patterns
    - Add JSDoc comments for functions and classes
    - Use Winston logger instead of console.log
    
  database:
    - Use better-sqlite3 for synchronous SQLite operations
    - Database runs in WAL mode for better concurrency
    - Store plugin configs in settings table
    
  socket_events:
    - Use Socket.io for real-time client-server communication
    - Emit events through PluginAPI.emit() for plugin compatibility
    - Listen to TikTok events via PluginAPI.registerTikTokEvent()
    
  testing:
    - Add tests in test/ directory or plugin-specific test/ folders
    - Follow existing test patterns (see plugins/new-soundboard/test/)
    - Run tests with node <test-file>.js
    
  security:
    - Never commit secrets or API keys
    - Use .env files for sensitive configuration
    - Follow rate limiting best practices
    - Sanitize user inputs

# Important Notes
notes:
  - The launcher.go file handles dependency installation automatically
  - Database is created automatically on first run
  - Plugins can be hot-loaded/reloaded without server restart
  - OBS Browser Source overlays are served from /overlay.html
  - TikTok session ID is required for LIVE connection
  - Multi-user profiles are supported via user_configs/
  - Cloud sync is available for OneDrive, Google Drive, Dropbox
  
# Useful Commands
commands:
  development:
    start_dev: npm run dev
    build_css: npm run build:css
    watch_css: npm run watch:css
    
  production:
    start: npm start
    
  launcher:
    compile_windows: go build -o start.exe launcher.go
    compile_linux: GOOS=linux go build -o start-linux launcher.go
    compile_mac: GOOS=darwin go build -o start-mac launcher.go
    
  testing:
    run_plugin_tests: node plugins/<plugin-name>/test/*.test.js
    
# References
references:
  documentation:
    - llm_start_here.md: Comprehensive developer guide for AI assistants
    - app/README.md: Full application documentation
    - app/CHANGELOG.md: Version history and changes
    - app/DEPLOYMENT_VERIFICATION_GUIDE.md: Deployment checklist
    - app/USER_CONFIG_STORAGE.md: User configuration documentation
    
  api:
    - PluginAPI: See modules/plugin-loader.js
    - Socket Events: See server.js for event definitions
    - Database Schema: Auto-created in database.js
    
# CI/CD
ci_cd:
  workflows:
    - soundboard-ci.yml: Runs tests and security checks for soundboard plugin
    
  testing_strategy:
    - Unit tests for validators and core functions
    - Security checks (npm audit, secret scanning)
    - Code quality checks (file sizes, code style)
    - File permission verification
    
  node_versions:
    - 18.x
    - 20.x
    - 22.x
